FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
USER root
RUN apt-get update
RUN apt-get update
RUN apt-get install -y python3-pip libpython3-dev vim rsync
RUN pip3 install flask